version: '3.9'
services:
  nexus:
    image: sonatype/nexus3
    container_name: artifacts_repository
    restart: always
    ports:
      # host_port:container_port
      - "8081:8081"

volumes:
  nexus-data: { }